import socket


# most code was generated by LLM, this is a demo.

def server():
    # 创建一个socket对象
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    # 获取本地主机名
    host = '0.0.0.0'

    port = 12345

    # 绑定端口号
    server_socket.bind((host, port))

    # 设置最大连接数，超过后排队
    server_socket.listen(5)

    while True:
        # 建立客户端连接
        client_socket, addr = server_socket.accept()
        print("连接地址: %s" % str(addr))

        data = client_socket.recv(1024).decode()
        print(f"收到客户端消息: {data}")

        message = "服务器已收到消息"
        client_socket.send(message.encode())

        client_socket.close()


if __name__ == '__main__':
    server()
