# the following is the code generated by gpt
import os


def update_labels_txt(labels_file, start_index, end_index, label):
    labels = {}
    if os.path.exists(labels_file):
        with open(labels_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                filename, existing_label = line.split(',')
                index = int(filename.split('.')[0])
                labels[index] = (filename, int(existing_label))

    for idx in range(start_index, end_index + 1):
        filename = f"{idx:09d}.png"  # 这里的格式必须与create_datasets.py里的保持一致，或者是与目标数据集的文件夹里的文件名保持一致
        labels[idx] = (filename, label)

    with open(labels_file, 'w') as f:
        for idx in sorted(labels.keys()):
            filename, label_value = labels[idx]
            f.write(f"{filename},{label_value}\n")

    print(f"已更新 {labels_file}，索引 {start_index}-{end_index} 的label设置为 {label}")


# 示例调用
if __name__ == "__main__":
    labels_file_path = '/Volumes/My Passport/dataset/kitti/data2/test/labels.txt'
    start_index = 101
    end_index = 205
    label = 1
    update_labels_txt(labels_file_path, start_index, end_index, label)
